# Generated by Django 5.0.6 on 2024-07-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture_score', models.FloatField(default=0)),
                ('posture_score', models.FloatField(default=0)),
                ('volume_score', models.FloatField(default=0)),
                ('pace_score', models.FloatField(default=0)),
                ('emotion_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('presentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='presentations.presentation')),
            ],
        ),
    ]
