# Generated by Django 5.0.6 on 2024-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
